name: Greeting on variable day

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday  ## 1) Workflow specific variable

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello  ## 2) Job specific variable
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK! -- ${goals}"
        env:
          First_Name: Mona  ## 3) for specific env variable
  
  second_job:
    runs-on: ubuntu-latest
    env:
      goals: 5344 
    steps:
      - name: "stp-1"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK! -- ${goals}"
  
  print_env_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Print All environment variable"
        run: env