name: Greeting on variable day

on:
  push

defaults:
  run:
    shell: python

env:
  PACE: 45.6
  MY_ORG: ${{ vars.HOBBY }}

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    environment: dev
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          # Maps TCP port 5432 in the service container to a randomly chosen available port on the host.
          - 5432    
    steps:
      - name: "Printing Job Context"
        run: |
          import json
          json.dumps(${{ toJSON(job) }})
          
        env:
          AGE: 303
          HOBBY: "SkyDiving"    