name: Greeting on variable day

on:
  push

env:
  PACE: 45.6

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Testing Env Variable -1 "
        run: |
          echo "MY_LANGAUGE -- ${var.MY_LANGAUGE} ➡️ (environment)"
          echo "SKILLS -- ${var.SKILLS} ➡️ (repo) "
          echo "HOBBY -- ${var.HOBBY} ➡️ (org) "
          echo "AGE -- ${var.AGE} ➡️ (common) "
          echo "PACE -- ${var.PACE} ➡️ (workflow) "
    
  second_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Overiding with Workflow Env Var "
        run: |
          echo "MY_LANGAUGE -- ${var.MY_LANGAUGE} ➡️ (environment)"
          echo "SKILLS -- ${var.SKILLS} ➡️ (repo) "
          echo "HOBBY -- ${var.HOBBY} ➡️ (org) "
          echo "AGE -- ${var.AGE} ➡️ (common) "
        env:
          AGE: 303
          HOBBY: "SkyDiving"    