name: Greeting on variable day

on:
  push

defaults:
  run:
    shell: bash

env:
  PACE: 45.6
  MY_ORG: ${{ vars.HOBBY }}

jobs:
  sample-job:
    runs-on: ubuntu-latest
    steps:
      - name: "sample-step"
        run: echo "hello"
  
  greeting_job:
    runs-on: ubuntu-latest
    needs: [sample-job]
    environment: dev
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          # Maps TCP port 5432 in the service container to a randomly chosen available port on the host.
          - 5432    
    steps:
      - name: "Printing github Context"
        run: |
          echo $GITHUB_CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: "Printing Job Context"
        run: |
          echo $JOB_CONTEXT
        env:
          AGE: 303
          HOBBY: "SkyDiving"
          JOB_CONTEXT: ${{ toJson(Job) }}