name: Flask App Workflow

on: push 

jobs:
  app-test:
    runs-on: ubuntu-latest
    services:
      mymongo:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: vegito
          MONGO_INITDB_ROOT_PASSWORD: veg@123
        ports:
          - 27017:27017
    steps:
      - name: Run App
        uses: docker://vegito/demoapp:player-ut-1.0
        with:
          entrypoint: python
          MONGO_URL: mongodb://mymongo:27017 
          MONGO_USERNAME: vegito
          MONGO_PASSWORD: veg@123 
          args: app.py