name: "Secrets Demo Workflow"

on: push

jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
       - name: "clone repo"
         run: |
            git clone "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
            ls -a
            pwd
            cd sonar-test
       - name: "decrypt secret"
         run: |
          pwd
          gpg --quiet --batch --yes  --decrypt --passphrase  --output /tmp/myprod.json prod.json.gpg
          cat /tmp/myprod.json