name: Greeting on variable day

on:
  push

env:
  AGE: 200

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Testing Env Variable -1 "
        run: |
          echo "MY_LANGAUGE -- ${MY_LANGAUGE} ➡️ (environment)"
          echo "SKILLS -- ${SKILLS} ➡️ (repo) "
          echo "HOBBY -- ${HOBBY} ➡️ (org) "
          echo "AGE -- ${AGE} ➡️ (common) "
    
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Overiding with Workflow Env Var "
        run: |
          echo "MY_LANGAUGE -- ${MY_LANGAUGE} ➡️ (environment)"
          echo "SKILLS -- ${SKILLS} ➡️ (repo) "
          echo "HOBBY -- ${HOBBY} ➡️ (org) "
          echo "AGE -- ${AGE} ➡️ (common) "
        env:
          AGE: 303
          HOBBY: "SkyDiving"