name: Flask App Workflow

on: push 

jobs:
  app-test:
    runs-on: ubuntu-latest
    services:
      app: 
        image: vegito/demoapp:player-ut-1.0
        env:
          MONGO_URL: mymongo://host.docker.internal:27017 
          MONGO_USERNAME: vegito
          MONGO_PASSWORD: veg@123 
        ports:
          - 5050:5000
        volumes:
          - my_docker_volume:/app
      mymongo:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: vegito
          MONGO_INITDB_ROOT_PASSWORD: veg@123
        ports:
          - 27017:27017
    steps:
      - name: Add user 
        run: |
          curl -X POST http://127.0.0.1:5050/api/player \
          -H "Content-Type: application/json" \
          -d '{
              "name": "Lionel Messi",
              "matches": 900,
              "goals": 860,
              "assists": 900,
              "club": "Inter Miami",
              "age": 40,
              "country": "Argentina"
          }'
      - name: Check User
        run: |
          curl -X GET http://127.0.0.1:5050/api/players
