name: Greeting on variable day

on:
  push

env:
  PACE: 45.6
  MY_ORG: ${{ vars.HOBBY }}

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: "Printing Job Context"
        run: toJSON(job)
        env:
          AGE: 303
          HOBBY: "SkyDiving"    